// Pricing table contract. Data files in data/pricing.<region>.json are
// generated by scripts/fetch-pricing.ts from the AWS Price List Bulk API.
// Never hardcode a price anywhere else; every entry keeps its sourceUrl.

export interface PriceEntry {
  /** Canonical key the engine looks up, e.g. "lambda.gbSecond.arm64". */
  key: string;
  /** USD per `unit`. */
  rate: number;
  unit: string;
  sku: string;
  description: string;
  /** The AWS Price List file this rate came from. */
  sourceUrl: string;
}

export interface PricingTable {
  region: string;
  generatedAt: string;
  source: string;
  entries: Record<string, PriceEntry>;
}

export class MissingPriceError extends Error {
  readonly key: string;
  readonly region: string;
  constructor(key: string, region: string) {
    super(
      `No price for "${key}" in region ${region}. ` +
        `Re-run scripts/fetch-pricing.ts or pick another region.`,
    );
    this.name = "MissingPriceError";
    this.key = key;
    this.region = region;
  }
}

export function price(table: PricingTable, key: string): PriceEntry {
  const entry = table.entries[key];
  if (!entry) throw new MissingPriceError(key, table.region);
  return entry;
}
