// CDK (TypeScript) export: one stack, one construct per node, derived from
// each service's defineService().cdk. The header lists every assumption
// and stub so the reader knows exactly what to replace.

import type { StateSnapshot } from "../model";
import type { PricingTable } from "../pricing";
import { monthlyTotal } from "../cost";
import { toMoney } from "../model";
import { defaultSettings } from "../defineService";
import { getService } from "../services";

const IMPORTS: Record<string, string> = {
  lambda: 'import * as lambda from "aws-cdk-lib/aws-lambda";',
  apigateway:
    'import * as apigateway from "aws-cdk-lib/aws-apigateway";\nimport * as apigwv2 from "aws-cdk-lib/aws-apigatewayv2";',
  dynamodb: 'import * as dynamodb from "aws-cdk-lib/aws-dynamodb";',
  s3: 'import * as s3 from "aws-cdk-lib/aws-s3";',
  cloudfront:
    'import * as cloudfront from "aws-cdk-lib/aws-cloudfront";\nimport * as origins from "aws-cdk-lib/aws-cloudfront-origins";',
  sqs: 'import * as sqs from "aws-cdk-lib/aws-sqs";',
  sns: 'import * as sns from "aws-cdk-lib/aws-sns";',
  eventbridge: 'import * as events from "aws-cdk-lib/aws-events";',
  stepfunctions: 'import * as sfn from "aws-cdk-lib/aws-stepfunctions";',
  cognito: 'import * as cognito from "aws-cdk-lib/aws-cognito";',
};

function varName(id: string): string {
  return id
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((w, i) => (i ? w[0].toUpperCase() + w.slice(1) : w))
    .join("")
    .replace(/^([0-9])/, "n$1");
}

function safeName(name: string): string {
  return name.replace(/[^a-zA-Z0-9._-]/g, "-").slice(0, 60) || "resource";
}

export function exportCdk(
  snapshot: StateSnapshot,
  pricing: PricingTable,
  stackName = "OverheadStack",
): string {
  const services = [...new Set(snapshot.nodes.map((n) => n.service))];
  const imports = services
    .map((s) => IMPORTS[s])
    .filter(Boolean)
    .join("\n");

  const blocks = snapshot.nodes
    .map((node) => {
      const def = getService(node.service);
      if (!def?.cdk) return `// ${node.name}: no CDK mapping`;
      const settings = { ...defaultSettings(def), ...node.settings };
      const code = def.cdk(settings, {
        varName: varName(node.id),
        resourceName: safeName(node.name),
      });
      return `// ── ${def.term}: ${node.name}\n${code}`;
    })
    .join("\n\n")
    .split("\n")
    .map((l) => (l ? `    ${l}` : l))
    .join("\n");

  const total = toMoney(monthlyTotal(snapshot, pricing)).toFixed(2);

  return `// Generated by Overhead — https://overhead-ecru.vercel.app
// Estimated monthly cost: $${total} (AWS Price List, ${pricing.region}, fetched ${pricing.generatedAt.slice(0, 10)})
//
// Assumptions and stubs to replace before deploying:
//   - Lambda handlers are inline stubs; wire real code assets.
//   - DynamoDB tables get a stub "pk" string partition key.
//   - CloudFront distributions point at a placeholder HTTP origin.
//   - REST APIs carry one mock ANY method so the stack synthesizes.
//   - Step Functions state machines hold a single Pass state.
//   - Wiring between constructs (permissions, event sources, targets)
//     is not generated — connect them for your use case.

import * as cdk from "aws-cdk-lib";
import { Construct } from "constructs";
${imports}

export class ${stackName} extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

${blocks}
  }
}
`;
}
