// CloudFormation export: the drawing as a template you can deploy.
//
// Two audiences in one file. CloudFormation reads `Resources` — emitted by
// each service's defineService().cfn(), so the template speaks the same
// vocabulary as the CDK export and the price model. Overhead reads
// `Metadata.Overhead` — the facts a template has no place for (positions,
// containers, sections, traffic, and the settings that only drive price),
// which is what makes the round-trip exact instead of approximate. A
// foreign template has no such block; importCloudFormation() then reads
// the resources structurally. Metadata is a legal template section and
// CloudFormation ignores it.

import type { StateSnapshot } from "../model";
import type { PricingTable } from "../pricing";
import type { CfnResource } from "../defineService";
import { monthlyTotal } from "../cost";
import { toMoney } from "../model";
import { defaultSettings } from "../defineService";
import { getService } from "../services";
import { toYamlDocument } from "../iac/yaml";

export const OVERHEAD_METADATA_KEY = "Overhead";
export const OVERHEAD_TEMPLATE_VERSION = 1;

/** PascalCase, alphanumeric — CloudFormation's rule for a logical id. */
export function logicalIdOf(raw: string): string {
  const id = raw
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join("");
  return /^[0-9]/.test(id) ? `R${id}` : id || "Resource";
}

/** Logical ids are unique per template · a suffix is added when they collide. */
export function logicalIds(ids: string[]): Map<string, string> {
  const out = new Map<string, string>();
  const used = new Set<string>();
  for (const id of ids) {
    const base = logicalIdOf(id);
    let name = base;
    let n = 2;
    while (used.has(name)) name = `${base}${n++}`;
    used.add(name);
    out.set(id, name);
  }
  return out;
}

/** The template as data · YAML and JSON are two renderings of this. */
export function cloudFormationTemplate(
  snapshot: StateSnapshot,
  pricing: PricingTable,
  title = "Architecture estimate",
): Record<string, unknown> {
  const ids = logicalIds(snapshot.nodes.map((n) => n.id));
  const Resources: Record<string, unknown> = {};
  const unmapped: string[] = [];

  for (const node of snapshot.nodes) {
    const def = getService(node.service);
    const logicalId = ids.get(node.id)!;
    if (!def?.cfn) {
      unmapped.push(node.name);
      continue;
    }
    const settings = { ...defaultSettings(def), ...node.settings };
    const emitted: CfnResource[] = def.cfn(settings, { logicalId, resourceName: safeName(node.name) });
    for (const r of emitted) {
      const key = r.suffix ? `${logicalId}${r.suffix}` : logicalId;
      // The node id rides on its own resource, so a template that has been
      // hand-edited or re-synthesised still matches back to this drawing.
      const meta = {
        ...(r.Metadata?.Overhead !== undefined ? { note: r.Metadata.Overhead } : {}),
        ...(r.suffix ? {} : { nodeId: node.id }),
      };
      Resources[key] = {
        Type: r.Type,
        Properties: r.Properties,
        ...(r.DependsOn?.length ? { DependsOn: r.DependsOn } : {}),
        ...(Object.keys(meta).length ? { Metadata: { [OVERHEAD_METADATA_KEY]: meta } } : {}),
      };
    }
  }

  const total = toMoney(monthlyTotal(snapshot, pricing));

  const template = {
    AWSTemplateFormatVersion: "2010-09-09",
    Description:
      `${title} · estimated $${total.toFixed(2)}/month (AWS Price List, ${pricing.region}, ` +
      `fetched ${pricing.generatedAt.slice(0, 10)}). Generated by Overhead.`,
    Metadata: {
      [OVERHEAD_METADATA_KEY]: {
        version: OVERHEAD_TEMPLATE_VERSION,
        drawing: title,
        region: pricing.region,
        estimatedMonthlyUsd: total,
        generator: "https://overhead-ecru.vercel.app",
        stubs: [
          "Wiring between resources (permissions, event sources, targets) is not generated.",
          "Lambda code is an inline stub; DynamoDB tables get a stub \"pk\" key; CloudFront points at a placeholder origin.",
          ...(unmapped.length ? [`No CloudFormation mapping: ${unmapped.join(", ")}.`] : []),
        ],
        traffic: snapshot.traffic,
        containers: snapshot.containers,
        sections: snapshot.sections,
        nodes: snapshot.nodes.map((n) => ({
          id: n.id,
          logicalId: ids.get(n.id),
          service: n.service,
          name: n.name,
          container: n.container,
          position: n.position,
          settings: n.settings,
          ...(n.card ? { card: n.card } : {}),
        })),
        edges: snapshot.edges,
      },
    },
    Resources,
    Outputs: {
      OverheadEstimatedMonthlyCost: {
        Description: `Overhead's estimate from the AWS Price List (${pricing.region}) · not a bill`,
        Value: total.toFixed(2),
      },
    },
  };

  return template;
}

/** YAML, because that is how people read and write CloudFormation. The
 *  same document in JSON is `JSON.stringify(cloudFormationTemplate(…))`,
 *  and the importer reads either. */
export function exportCloudFormation(
  snapshot: StateSnapshot,
  pricing: PricingTable,
  title = "Architecture estimate",
): string {
  return toYamlDocument(cloudFormationTemplate(snapshot, pricing, title));
}

function safeName(name: string): string {
  return name.replace(/[^a-zA-Z0-9._-]/g, "-").slice(0, 60) || "resource";
}
